
platform :ios, '13.0'
target 'CometChatPro-PushNotification-SampleApp' do
    use_frameworks!
        pod 'CometChatPro','3.0.906'
        pod 'CometChatCalls','2.2.0'
        pod 'Firebase'
        pod 'FirebaseMessaging'

end

target 'NotificationServiceExtension' do
        use_frameworks! 
        pod 'CometChatPro','3.0.906'
        pod 'CometChatCalls','2.2.0'
        pod 'Firebase'
        pod 'FirebaseMessaging'
end
