platform :ios, '13.0'

target 'PushNotificationSample-APNS' do
        use_frameworks!
        pod 'CometChatPro','3.0.909'
        pod 'CometChatCalls','2.2.0'
end

target 'NotificationServiceExtension' do
        use_frameworks!
        pod 'CometChatPro','3.0.909'
        pod 'CometChatCalls','2.2.0'
end
