

target 'PushNotificationSample-APNS' do
        pod 'CometChatPro','3.0.1'
        pod 'CometChatCalls','2.1.0'
end

target 'NotificationServiceExtension' do
        pod 'CometChatPro','3.0.1'
        pod 'CometChatCalls','2.1.0'
end