

target 'PushNotificationSample-APNS' do
        pod 'CometChatPro','3.0.900'
        pod 'CometChatCalls','2.1.0'
end

target 'NotificationServiceExtension' do
        pod 'CometChatPro','3.0.900'
        pod 'CometChatCalls','2.1.1'
end
